### ISSUE TITLE
IdGlobal.pas compile Error in Delphi 10.4 Sydney

### ISSUE THREAD

**Issue by athlo** [graemeg/indy#2]
In Delphi 10.4 is AUTOREFCOUNT not defined, therefore it is not possible IdGlobal to compile, while USE_OBJECT_ARC is not defined. 

http://docwiki.embarcadero.com/RADStudio/Sydney/en/Conditional_compilation_(Delphi)

**Comment by athlo** [comment]
The same for NEXTGEN

**Comment by graemeg** [comment]
Thank you for the report, but unfortunately this is only an unofficial Git mirror repository of the original SVN repo. You'll have to contact the folks at www.indyproject.org to report bugs or submit patches. They have a web forum and NNTP newsgroup where you could do so.

**Comment by athlo** [comment]
This repository is not newest version of Indy, Delphi 10.4.1 have newer version.
