### ISSUE TITLE
IdGlobalProtocols.pas -> IndyComputerName returns an empty string

### ISSUE THREAD

**Issue by MPannier** [graemeg/indy#3]
Should it be

  i := MAX_COMPUTERNAME_LENGTH **+ 1**;
  if {$IFDEF STRING_IS_UNICODE}GetComputerNameW{$ELSE}GetComputerNameA{$ENDIF}(LHost, i) then begin

instead of

  i := MAX_COMPUTERNAME_LENGTH;
  if {$IFDEF STRING_IS_UNICODE}GetComputerNameW{$ELSE}GetComputerNameA{$ENDIF}(LHost, i) then begin

Starting Line 5028?

**Comment by graemeg** [comment]
Hi. Thank you for taking the time to report the issue. Unfortunately this is an unofficial read-only Git mirror - for my personal use. You will have to report Indy issues on their NNTP News Server, or web forum. I'm closing this ticket, but it will still be viewable, so you could reference it in your message to them if you wanted.
